---
name: XML-Grammar-ProductsSyndication
version: 0.02
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: an XML Grammar for ProductsSyndication.
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
build_requires:
  Imager: 0
  LWP::UserAgent: 0
  Moose: 0
  Test::More: 0
  Test::XML: 0
  XML::Amazon: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
provides:
  XML::Grammar::ProductsSyndication:
    file: lib/XML/Grammar/ProductsSyndication.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
